# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='\u8bf7\u6c42\u6d88\u606f')),
                ('type', models.IntegerField(max_length=10, verbose_name='\u6d88\u606f\u7c7b\u578b')),
                ('message', models.CharField(max_length=128, null=True, verbose_name='\u8fd4\u56de\u6d88\u606f')),
                ('senstive', models.CharField(max_length=128, null=True, verbose_name='\u654f\u611f\u6307\u6570')),
                ('nonsensitive', models.CharField(max_length=128, null=True, verbose_name='\u975e\u654f\u611f\u6307\u6570')),
                ('codedesc', models.CharField(max_length=128, null=True, verbose_name='\u6d88\u606f\u63cf\u8ff0')),
                ('ip', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'sensitive content detection',
            },
        ),
    ]
