# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensmod',
            name='type',
            field=models.IntegerField(verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
