# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensapi', '0002_auto_20180402_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensmod',
            old_name='senstive',
            new_name='sensitive',
        ),
    ]
